export default {
  login: "paulahage",
  id: 84124999,
  node_id: "MDQ6VXNlcjg0MTI0OTk5",
  avatar_url: "https://avatars.githubusercontent.com/u/84124999?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/paulahage",
  html_url: "https://github.com/paulahage",
  followers_url: "https://api.github.com/users/paulahage/followers",
  following_url:
    "https://api.github.com/users/paulahage/following{/other_user}",
  gists_url: "https://api.github.com/users/paulahage/gists{/gist_id}",
  starred_url: "https://api.github.com/users/paulahage/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/paulahage/subscriptions",
  organizations_url: "https://api.github.com/users/paulahage/orgs",
  repos_url: "https://api.github.com/users/paulahage/repos",
  events_url: "https://api.github.com/users/paulahage/events{/privacy}",
  received_events_url: "https://api.github.com/users/paulahage/received_events",
  type: "User",
  site_admin: false,
  name: "Paula Hage",
  company: null,
  blog: "",
  location: "Rotterdam",
  email: null,
  hireable: null,
  bio: "Hi! I'm Paula 🙋‍♀️\r\na marketing and communication professional learning to code!",
  twitter_username: null,
  public_repos: 6,
  public_gists: 0,
  followers: 2,
  following: 5,
  created_at: "2021-05-13T08:38:51Z",
  updated_at: "2021-12-22T13:45:19Z",
};


//login: 'john-smilga',
  // id: 42133389,
  // node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  // avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  // gravatar_id: '',
  // url: 'https://api.github.com/users/paulahage',
  // html_url: 'https://github.com/john-smilga',
  // followers_url: 'https://api.github.com/users/john-smilga/followers',
  // following_url:
  //   'https://api.github.com/users/john-smilga/following{/other_user}',
  // gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  // starred_url:
  //   'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  // subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  // organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  // repos_url: 'https://api.github.com/users/john-smilga/repos',
  // events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  // received_events_url:
  //   'https://api.github.com/users/john-smilga/received_events',
  // type: 'User',
  // site_admin: false,
  // name: 'John Smilga',
  // company: 'Coding Addict',
  // blog: 'www.johnsmilga.com',
  // location: 'Los Angeles',
  // email: null,
  // hireable: null,
  // bio: 'Creator of Coding Addict',
  // twitter_username: 'john_smilga',
  // public_repos: 152,
  // public_gists: 0,
  // followers: 1495,
  // following: 0,
  // created_at: '2018-08-06T06:48:23Z',
  // updated_at: '2020-07-08T05:01:32Z',
